version: 2
updates:
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
